<?php

/**
 * @file
 * Primary module hooks for Webform Composite test module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 *
 * @file
 * Provides an example that shows how to create a Webform composite.
 */
module_load_include('inc', 'webform', 'includes/webform.theme.template');

/**
 * Implements hook_theme().
 */
function webform_composite_test_theme()
{
  return [
    'webform_composite_test' => [
      'render element' => 'element'
    ],
    'webform_composite_test_recap' => [
      'render element' => 'element'
    ]
  ];
}

/**
 * Prepares variables for webform example composite templates.
 *
 * Default template: webform-example-composite.html.twig.
 *
 * @param array $variables
 *          An associative array containing:
 *          - element: An associative array containing the properties of the element.
 */
function template_preprocess_webform_composite_test(array &$variables)
{
  // Here you can get the composite element and alter it.
  _template_preprocess_webform_composite($variables);
}